{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.thk-im",
    "module": "preview",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "preview-0.5.9.aar",
          "url": "preview-0.5.9.aar",
          "size": 111821,
          "sha512": "6acf176b21b7802a179a5e707efca8fb0df731e546598af98cc5e664ec6f3e3544c8f36c7ab51e0803a7296281b89b5b50b2fdef17109782732d4d75cad09792",
          "sha256": "d3a1eb4989031f75f452ecb7d06efb97dc5f65e949f0b628e19ad47ba81cacb9",
          "sha1": "99b33f622666ce3e35c6739807ece15cfe54cad3",
          "md5": "f1955e4ea15f43c7861b1889d3eb7c75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.github.getActivity",
          "module": "XXPermissions",
          "version": {
            "requires": "25.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.danikula",
          "module": "videocache",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "io.github.thk-im",
          "module": "core",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "io.github.thk-im",
          "module": "ui",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "preview-0.5.9.aar",
          "url": "preview-0.5.9.aar",
          "size": 111821,
          "sha512": "6acf176b21b7802a179a5e707efca8fb0df731e546598af98cc5e664ec6f3e3544c8f36c7ab51e0803a7296281b89b5b50b2fdef17109782732d4d75cad09792",
          "sha256": "d3a1eb4989031f75f452ecb7d06efb97dc5f65e949f0b628e19ad47ba81cacb9",
          "sha1": "99b33f622666ce3e35c6739807ece15cfe54cad3",
          "md5": "f1955e4ea15f43c7861b1889d3eb7c75"
        }
      ]
    }
  ]
}
