{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.thk-im",
    "module": "ui",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.5.9.aar",
          "url": "ui-0.5.9.aar",
          "size": 577932,
          "sha512": "94eee6396532d83826a873b2aa936f1a5f0868f6a6059400e50843657114d38c0098b640fe3dc3ee36e5b3dde9c158f43efd75ff1625ced2cbee7542f482e046",
          "sha256": "c6cf61ac57e25852f1824be0fc595d20e88062c33b26e595b85d1eca17782882",
          "sha1": "c62fef86e195417f5e8fb90a71d7f31e8f8a32a8",
          "md5": "2f14fb7b65801d969d04c1852424a48b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.github.getActivity",
          "module": "XXPermissions",
          "version": {
            "requires": "25.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.aitsuki",
          "module": "SwipeMenuRecyclerView",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "com.github.li-xiaojun",
          "module": "XPopup",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.thk-im",
          "module": "core",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-0.5.9.aar",
          "url": "ui-0.5.9.aar",
          "size": 577932,
          "sha512": "94eee6396532d83826a873b2aa936f1a5f0868f6a6059400e50843657114d38c0098b640fe3dc3ee36e5b3dde9c158f43efd75ff1625ced2cbee7542f482e046",
          "sha256": "c6cf61ac57e25852f1824be0fc595d20e88062c33b26e595b85d1eca17782882",
          "sha1": "c62fef86e195417f5e8fb90a71d7f31e8f8a32a8",
          "md5": "2f14fb7b65801d969d04c1852424a48b"
        }
      ]
    }
  ]
}
